### ISSUE TITLE
Impact of changes to sliders

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#107]
Coming up as $NaN/year instead of the numerical value.  (see guelph.citizenbudget.com)

Also in the preference summary chart (see aurora.citizenbudget.com)

It's not keeping a running total as you go through the exercise anymore.

**Comment by lharv076** [comment]
@gmattar Claudio said you'd be manually changing some of the JS in the consultations directly in the application. If you want, you can change one of them and see if it works, and I'll go ahead and do the rest for you.

If you're changing a line of code that is already documented in the wiki, make sure you update the wiki as well.

Thanks!

**Comment by lharv076** [comment]
@gmattar It's still affecting Coquitlam's temporary link (http://coquitlam.citizenbudget.com/?token=xq8imxfrs59UCZ9EssY9) but not the live one. 

It's the only one not working.

**Comment by gmattar** [comment]
I updated Coquitlam's custom javascript yesterday, it should have fixed this. In fact, the link you shared above is ok here. Is this bug still happening to you?

**Comment by lharv076** [comment]
The live link works (coquitlam.citizenbudget.com) but the temporary link
doesn't (http://coquitlam.citizenbudget.com/?token=xq8imxfrs59UCZ9EssY9).

It's not a huge deal, but it's just strange.

On Fri, Apr 8, 2016 at 11:31 AM, Guilherme Mattar Bastos <
notifications@github.com> wrote:

> I updated Coquitlam's custom javascript yesterday, it should have fixed
> this. In fact, the link you shared above is ok here. Is this bug still
> happening to you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/citizenbudgetapp.com/issues/107#issuecomment-207479951>
>



-- 
*Laurence Harvey Leclerc*
Product Development Manager
1.888.750.4980 x. 706

Citizen Budget <http://www.citizenbudget.com> / Budget Citoyen
<http://www.budgetcitoyen.com>
opennorth.ca / nordouvert.ca

**Comment by lharv076** [comment]
@gmattar The changes aren't being reflected in some of the temporary links, and they have to because we use these to send examples to clients. 

Ex: the description is fixed for digbymuni.citizenbudget.com but not http://digbymuni.citizenbudget.com/?token=RC4g3qoqeA4K3QJTZJp3

Also, what's going on with http://en.budgetcitoyenscdn-ndg.com/?token=yb4tKegDpyFNkqZXho9i ?

**Comment by gmattar** [comment]
Weird, here both digbymuni links look the same. Could you test the temporary link in an incognito tab or reset the browser cache?

I'll check  en.budgetcitoyenscdn-ndg.com

**Comment by lharv076** [comment]
Aha! Yes it worked in my incognito. I'll reset my browser cache, thanks :)

On Fri, Apr 8, 2016 at 1:29 PM, Guilherme Mattar Bastos <
notifications@github.com> wrote:

> Weird, here both digbymuni links look the same. Could you test the
> temporary link in an incognito tab or reset the browser cache?
>
> I'll check en.budgetcitoyenscdn-ndg.com
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/citizenbudgetapp.com/issues/107#issuecomment-207526925>
>



-- 
*Laurence Harvey Leclerc*
Product Development Manager
1.888.750.4980 x. 706

Citizen Budget <http://www.citizenbudget.com> / Budget Citoyen
<http://www.budgetcitoyen.com>
opennorth.ca / nordouvert.ca

**Comment by lharv076** [comment]
Closing and opening new issue for http://en.budgetcitoyenscdn-ndg.com/?token=yb4tKegDpyFNkqZXho9i
