### ISSUE TITLE
Explanation text for each widget

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#113]
**1. Sliders (both percentage and regular)**
FR: Bouger le glisseur à droite ou à gauche selon vos priorités
EN: Move the slider to the right or left according to your priorities

**2. On/Off switch**
FR: Basculez l'interrupteur selon vos priorités
EN: Flip the switch according to your priorities

**3. Radio buttons (budgetary and non-budgetary), the dropdown list and the conditional questions widget**
FR: Sélectionnez une option
EN: Select an option

**4. Check box (if it's checked by default)**
FR: Décochez la boîte selon vos priorités
EN: Uncheck the box according to your priorities

**5. Check box (if it's not checked by default)**
FR: Cochez la boîte selon vos priorités
EN: Check the box according to your priorities

**6. Check boxes** 
FR: Sélectionnez une ou plusieurs options
EN: Select one or more options

**7. Text box and area**
FR: Laissez un commentaire
EN: Leave a comment

**Comment by lharv076** [comment]
@claudioccm @gmattar

**Comment by claudioccm** [comment]
Thank you!

**Comment by lharv076** [comment]
@claudioccm Can I close this issue?
