### ISSUE TITLE
Slider bubble values

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#121]
1. "Services" module default bubble shows the whole amount, in one condensed line. Normal formatted numbers only appear once you start moving the slider. It should show either (for example) "200k" or 200,000 right from the get-go.

2. "Tax" module default bubble value shows "1". Numbers only appear once you start moving the slider. The number in the bubble for the default position should be displayed from the get-go (e.g. $200)

#120

**Comment by lharv076** [comment]
@claudioccm Hey, a minor detail with the new sliders that needs to be fixed. No "same day" rush, but should still be fixed soon.

Thanks!

**Comment by lharv076** [comment]
@claudioccm Can you look into this this week?

**Comment by lharv076** [comment]
@gmattar Hows this going?

**Comment by lharv076** [comment]
@claudioccm @gmattar 

As you fix this, can you also put the line back in that shows where the default position of the slider is? When you move it, you lose the reference. 

We have a client doing a presentation of their tool, so it needs to be done by the end of the week. Can you confirm that you've seen this? 

Thanks!

**Comment by gmattar** [comment]
Confirmed! I'm working on it right now

**Comment by lharv076** [comment]
Excellent! Thanks.

On Wed, May 4, 2016 at 3:48 PM, Guilherme Mattar Bastos <
notifications@github.com> wrote:

> Confirmed! I'm working on it right now
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/citizenbudgetapp.com/issues/121#issuecomment-216980990>
>



-- 
*​*

*If you're at the GFOA in Toronto come by ​the Exhibit Hall ​and say hi
to ​us at booth #508! *

*Laurence Harvey Leclerc*
Product Development Manager
Open North / Citizen Budget
1.888.750.4980 x. 706

Visit our NEW website - http://citizenbudget.com
@opennorth
