### ISSUE TITLE
Google Charts aren't appearing on the dashboard

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#132]
<img width="627" alt="screen shot 2016-06-30 at 8 23 30 am" src="https://cloud.githubusercontent.com/assets/13963466/16487974/08095716-3e9c-11e6-9510-5553f28d3444.png">

Affecting both applications, all live consultations:

http://ca1.opennorth.ca/admin/dashboard/summary?id=56c33a65a7ceae3894000ba9

**Comment by lharv076** [comment]
It's happening with the front-end consultation pie charts now as well:

http://aurora.citizenbudget.com/?token=ac36XVAJyKn6xKxgAoEi

@claudioccm

**Comment by lharv076** [comment]
Alright so I fixed the issue with the front-end consultation pie charts. We just have to replace '1' with '1.1' in the following bit of code:

google.load 'visualization', '1.1',
  callback: ->
    drawChart 'chart1'
    drawChart 'chart2'

However, I don't know how to change it to fix the dashboard.

**Comment by cmonagle** [comment]
This appears to have been resolved, though I can't pinpoint the commit.
