### ISSUE TITLE
Problems deploying to ca1.opennorth.ca

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#136]
@jpmckinney We're trying to deploy two new PRs to ca1.opennorth.ca. Everything worked fine for ca3 but the changes aren't taking hold for ca1. Can you help?

@andrefarzat Can you explain the problem more in detail?

**Comment by andrefarzat** [comment]
Sure. I deployed to `ca1` using the `git push ca1 master` command from my local machine and it followed the `post-commit` script which didn't compiled the assets (as the ca3 machine did). So I ran the command manually (`RAILS_ENV=production bundle exec rake assets:precompile` and `cp -rf $HOME/citizenbudget/public/. /srv/www/citizenbudget.com/public`) and restarted the server (`sudo stop citizenbudget` and `sudo start citizenbudget` ) but the changes weren't applied in the server. 

As a last try I made the script behave exactly as the `ca3` script (removing the conditional which didn't make the script to run the command to compile ) and, during the `git push ca1 master` it ran exactly as the ca3 ran, but still no success updating the assets in prod.

Are we missing something?

**Comment by lharv076** [comment]
@gmattar Tagging you in case you have an idea

**Comment by gmattar** [comment]
did you update `/config/initializers/rails_app_version.rb`?

See https://github.com/opennorth/citizenbudgetapp.com/wiki/Common-developer-tasks-%28Deprecated%29#expire-caches-in-production

**Comment by jpmckinney** [comment]
I don’t know if anyone’s played with the authorized_keys files but I can’t log in to either server at the moment.

**Comment by lharv076** [comment]
@andrefarzat See James' comment above. Did you do anything when trying to access it yetsterday?

**Comment by andrefarzat** [comment]
@lharv076 + @jpmckinney the only thing I did was change the `post-commit` script in the ca1 machine (to make it conform with ca3 script). I just tried to ssh to ca1 with the key you gave me Yesterday and I got it. Perhaps the key is outdated or the ssh agent isn't started or doesn't have the key added ?

**Comment by lharv076** [comment]
Alright all, the changes took effect. I don't know which one of you fixed it, but thank you!
