### ISSUE TITLE
Ability to move property assessment input

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#70]
Currently, moving it above the navigation bar puts it outside the `<form>` tag, which means it doesn't get submitted. Moving the opening `<form>` tag earlier (possibly to include the entire page) will enable CoffeScript customizations to move the input above the navigation bar.

**Comment by lharv076** [comment]
@claudioccm 

Can you put the snippit of JS here?

**Comment by claudioccm** [comment]
@lharv076, this is the new code you will need to use. Just keep in mind that you will need to replace the "ID" part with the actual id of the form. Let me know if you have problems with that. 
```
$('#assessment').css('margin-top', '1em').insertBefore('#Expenses');
$('#assessment input').attr('form', $('form').attr('ID'));
```
