### ISSUE TITLE
Mongoid::MultiParameterAttributes

### ISSUE THREAD

**Issue by phildionne** [opennorth/citizenbudgetapp.com#79]
Related to #81 

It seems like Mongoid 4 removed MultiParameterAttributes support and nothing seems to exist to replace it.

See:
- http://stackoverflow.com/questions/28016853/mongoid-4-multiparameter-attributes-with-rails-4
- https://github.com/rails/rails/pull/8189

This module is only included here https://github.com/opennorth/citizenbudgetapp.com/blob/master/app/models/questionnaire.rb#L7 and I'm not too sure of what it is supposed to be used for nor if it is used by the model.

There is a quick n' dirty solution here: https://gist.github.com/mhuggins/6c3d343fd800cf88f28e but I think it only applies to ActiveRecord.

Before investing more time on this issue, @jpmckinney could you please confirm it is indeed useful and present the possible workarounds. Thanks!

**Comment by jpmckinney** [comment]
I think it is used so that when dates are submitted (using three dropdowns) they are auto-magically interpreted by MultiParameterAttributes.

**Comment by jpmckinney** [comment]
A solution may be to just change the date inputs to something that works without this module.

**Comment by phildionne** [comment]
This won't be an issue anymore, thanks to #82
