### ISSUE TITLE
ActiveAdmin & Mongoid

### ISSUE THREAD

**Issue by phildionne** [opennorth/citizenbudgetapp.com#80]
Related to #81 

One of the application's dependencies [activeadmin-mongoid ](https://github.com/elia/activeadmin-mongoid]) is deprecated and is locked with mongoid 2, which makes it unusable with newer versions of mongoid.

There has been some work towards supporting mongoid directly in activeadmin: https://github.com/activeadmin/activeadmin/issues/2714 but at the moment it seems on hold.

I'm questioning the viability of updating both activeadmin and mongoid if support is not yet available. Furthermore, in the scope of this project and organisation I assume contributing to activeadmin to enable mongoid support is out of scope.

@jpmckinney This is one of the subjects I'd like to discuss with you.

**Comment by jpmckinney** [comment]
Have you seen this issue? https://github.com/opennorth/citizenbudgetapp.com/issues/67 It documents some of this.

**Comment by seanlinsley** [comment]
Hi there, I followed the Github link from https://github.com/activeadmin/activeadmin/issues/2714. Is there a possibility to fund the work to provide official ActiveAdmin support for Mongoid? So much has already been done that I don't believe it would be too difficult, but it does take time and concentration.

**Comment by jpmckinney** [comment]
This project is moving to PostgreSQL, so we won't be investing more time in Mongoid.

**Comment by seanlinsley** [comment]
:+1: that's what I'd do in your situation
