### ISSUE TITLE
Investigate if SpeakerDeck embed is still an issue

### ISSUE THREAD

**Issue by phildionne** [opennorth/citizenbudgetapp.com#86]
This article https://github.com/opennorth/citizenbudgetapp.com/wiki/Adding-Speaker-Deck-embeds explains the issue, I'm wondering if it's still an issue. Looking to reduce custom elements in the codebase.

**Comment by jpmckinney** [comment]
We haven't used SpeakerDeck in years, so fine to cut.

**Comment by phildionne** [comment]
Great
