### ISSUE TITLE
Render coffeescript in views

### ISSUE THREAD

**Issue by phildionne** [opennorth/citizenbudgetapp.com#88]
Switching from HAML to ERB forces us to find an alternative to the `haml-coffee` gem. The logical answer would be to use [execjs](https://github.com/rails/execjs).

I've tried to make it work by first trying this but it doesn't work:

```erb
<%= ExecJS.compile(@questionnaire.javascript).call %>
```

I guess it is related to serialization or string escaping. Does anyone has any idea of making this work?

@jpmckinney

**Comment by jpmckinney** [comment]
@questionnaire.javascript is in fact CoffeeScript, so you need a Coffeescript-to-Javascript compiler.

**Comment by phildionne** [comment]
Found a solution using https://github.com/josh/ruby-coffee-script
